version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_ssl
    ports:
      - "5671:5671"  # Expose RabbitMQ SSL port
      - "15672:15672"
    volumes:
      - ./certs:/etc/rabbitmq/certs
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
